stages:
  - preview

preview:
  stage: preview
  before_script:
    - apk update && apk add bash && apk add --update coreutils
    - pip install apprise && pip install awscli
    - aws s3 ls s3://embily-staging-core-backup/db_backups
    - aws s3 ls ${WALG_S3_PREFIX}/validate_metadata/
    - DIFF=$(( ($(date -d $(date +%Y%m%d) +%s) - $(date -d $(aws s3 ls s3://embily-staging-core-backup/db_backups/validate_metadata/ | awk '{print $1}'| tail -n 1) +%s) )/(60*60) ))
    - echo $DIFF
  script:
    - aws s3 cp ${WALG_S3_PREFIX}/test_metadata/$(aws s3 ls s3://embily-staging-core-backup/db_backups/test_metadata/ | tail -n 1 | awk '{print $4}') ./backup_report
    - aws s3 cp ${WALG_S3_PREFIX}/validate_metadata/$(aws s3 ls s3://embily-staging-core-backup/db_backups/validate_metadata/ | tail -n 1 | awk '{print $4}') ./backup_report
    - ls
    - echo $credantionals_json
    - cat $credantionals_json

