stages:
  - preview

preview:
  stage: preview
  before_script:
    - |
      echo "Install dependencies"
      apk update && apk add bash && apk add --update coreutils
      pip install apprise && pip install awscli && pip install oauth2client && pip install gspread
    - |
      aws s3 ls ${WALG_S3_PREFIX}  #Check bucket is present
      export LAST_VALIDATION=$( aws s3 ls s3://embily-staging-core-backup/db_backups/validate_metadata/ | tail -n 1 ) || true #Check validation is present
      if [[ -z $LAST_VALIDATION ]]; then
        export DIFF_DAYS=1000
      else 
        CURRENT_DATE=$(date -d $(date +%Y%m%d) +%s)
        LAST_DATE_OF_VALIDATION=$(date -d $(echo $LAST_VALIDATION | awk '{print $1}') +%s)
        DIFF_TIME=$(( $CURRENT_DATE - $LAST_DATE_OF_VALIDATION ))
        export LAST_VALIDATION_FILE=$(echo $LAST_VALIDATION | awk '{print $4}')
        export DIFF_DAYS=$(( $DIFF_TIME/(60*60*24) ))
        echo $DIFF_DAYS
      fi
  script:
    - echo $credantionals_json > credantionals.json
    - >
      if [[ $DIFF_DAYS -gt $INTERVAL_DAYS ]]; then 
        echo 'Start validation'
        # export VALIDATED_BACKUP="some_validated_backup"
        # printf '{"tested_backup": "%s", "last_validation": "%s"}' $VALIDATED_BACKUP $(date '+%Y-%m-%dT%H:%M:%S')' > ./validate_report.json
        # aws s3 cp validate_report.json ${WALG_S3_PREFIX}/validate_metadata/
        # aws s3 cp ${WALG_S3_PREFIX}/test_metadata/$(aws s3 ls ${WALG_S3_PREFIX}/test_metadata/ | tail -n 1 | awk '{print $4}') ./backup_report.json
        # ./sheets.py
      else
        # aws s3 cp ${WALG_S3_PREFIX}/test_metadata/$(aws s3 ls ${WALG_S3_PREFIX}/test_metadata/ | tail -n 1 | awk '{print $4}') ./backup_report.json
        # aws s3 cp ${WALG_S3_PREFIX}/validate_metadata/$(aws s3 ls s${WALG_S3_PREFIX}/db_backups/validate_metadata/ | tail -n 1 | awk '{print $4}') ./validate_report.json
        # echo "No Validation"
      fi
  # after_script:
  #   - >
  #     if [ $CI_JOB_STATUS == 'success' ]; then
  #       echo 'This will only run on success'
  #     else
  #       echo 'apprise  -t "Achtung!Alarm!Внимание!Failed checkout POSTGESQL files" -b "$CI_JOB_URL" "${APPRISE}"'
  #       printf '{"tested_backup": "Failed", "last_validation": "%s"}' $(date '+%Y-%m-%dT%H:%M:%S')' > ./validate_report.json
  #       aws s3 cp validate_report.json ${WALG_S3_PREFIX}/validate_metadata/
  #       aws s3 cp ${WALG_S3_PREFIX}/test_metadata/$(aws s3 ls ${WALG_S3_PREFIX}/test_metadata/ | tail -n 1 | awk '{print $4}') ./backup_report.json
  #       ./sheets.py
  #     fi



    # - aws s3 cp ${WALG_S3_PREFIX}/test_metadata/$(aws s3 ls s3://embily-staging-core-backup/db_backups/test_metadata/ | tail -n 1 | awk '{print $4}') ./backup_report.json
    # - aws s3 cp ${WALG_S3_PREFIX}/validate_metadata/$(aws s3 ls s3://embily-staging-core-backup/db_backups/validate_metadata/ | tail -n 1 | awk '{print $4}') ./validate_report.json
    # - echo $credantionals_json > credantionals.json
    # - ls
    # - ./sheets.py


   # - aws s3 cp ${WALG_S3_PREFIX}/test_metadata/$(aws s3 ls s3://embily-staging-core-backup/db_backups/test_metadata/ | tail -n 1 | awk '{print $4}') ./backup_report.json