version: "3.6"
services:
  database:
    container_name: postgres
    image: harbor.oom.ag/library/postgres_with_wal-g:12.8
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      PGHOST: /var/run/postgresql
      PGDATA: /var/lib/postgresql/data
      PGUSER: core_staging
      WALG_S3_PREFIX: ${WALG_S3_PREFIX}
      RECOVERY_WALG: 'true'
      PGDATABASE: core_staging
      ARCHIVE_MODE: 'off'

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 120